# Created on 3 December 2019
# Contains the ids for every item in the game

DIRT = 0
STONE = 1
TEST_SWORD = 2
TEST_PICKAXE = 3
CAT = 4
ZOMBIE = 5
DIMENSION_HOPPER = 6
DIMENSION_CREATOR = 7
CHEST = 8
SNOW = 9
DEMATERIALIZER = 10
TIME_WARP = 11
WORLD_BUILDER = 12
FOREST = 13
MOUNTAIN = 14
VALLEY = 15
